version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source code dependencies...
      - yarn install
  build:
    commands:
      - echo Building the code...
      - yarn build
  post_build:
    commands:
      - echo Emptying the S3 bucket...
      - aws s3 rm s3://lkksoftdev-vsbba-fe --recursive
      - echo Copying the build output to the S3 bucket...
      - aws s3 sync dist s3://lkksoftdev-vsbba-fe

#artifacts:
#  files:
#    - '**/*'
#  base-directory: 'dist' # replace with your build output directory
